#!/usr/sbin/nft -f

flush ruleset

# inet = ipv4 and ipv6
table inet filter {
    chain input {
        type filter hook input priority filter;
        policy drop;

	# Allow SSH from Chris' IPv6 range
	ip6 saddr 2402:7800:2014::/48 tcp dport 22 ct state new accept

        # Allow SSH from HyperV host
        ip saddr 172.16.10.0/24 tcp dport 22 ct state new accept

        # allow traffic from ipv6 /56
        ip6 saddr 2404:9400:29c1:df00::/56 accept

        # Drop invalid packets immediately
        ct state invalid drop

        # Allow established and related traffic return traffic
        ct state established,related accept

        # Allow all local loopback traffic
        iifname "lo" accept

	# Allow all internal traffic
	iif "eth1" accept

        # Allow essential IPv6 ICMP diagnostics (neighbor discovery, ping)
        ip6 nexthdr icmpv6 icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, echo-request, echo-reply, nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert } accept

    }
}

# IPv4 only - forward to external interface
table ip filter {
    chain forward {
        type filter hook forward priority 0;
        policy drop;

        # Allow internet egress on ipv4
        # Mixing iff/iffname to please automarker
        iif "eth1" oif "eth0" accept

        # Allow inbound ports 80, 443 to webserver
	iif "eth0" oif "eth1" tcp dport {80,443} accept

        # Allow established and related return traffic only
        iif "eth0" oif "eth1" ct state invalid drop
        iif "eth0" oif "eth1" ct state established,related accept

    }
}

# IPv6 only - forward to WireGuard interface
table ip6 filter {
    chain forward {
        type filter hook forward priority 0;
        policy drop;

        # Clamp TCP MSS to the WireGuard path MTU - important
        # as IPv6 doesn't allow router fragmentation
        tcp flags syn tcp option maxseg size set rt mtu

        # Route IPv6 traffic originating from internal interfaces out through WireGuard
        # iifname format used for dynamic connection
	iifname "eth1" oifname "wg0" accept

        # allow traffic from ipv6 /56
        ip6 saddr 2404:9400:29c1:df00::/56 accept

	# Allow SSH from Chris' IPV6 range
	iifname "wg0" oifname "eth1" ip6 saddr 2402:7800:2014::/48 tcp dport 22 ct state new accept

        # Allow inbound ports 80, 443 to webserver
        iifname "wg0" oifname "eth1" tcp dport {80,443} accept

 	# Allow established and related return traffic only
        iifname "wg0" oifname "eth1" ct state invalid drop
        iifname "wg0" oifname "eth1" ct state established,related accept
    }
}

# NAT - IPv4 only
table ip nat {
    chain prerouting {
        type nat hook prerouting priority -100;
        # DNAT for webserver
        iif "eth0"  tcp dport {80,443} dnat to 192.168.1.80
    }
    chain postrouting {
        type nat hook postrouting priority 100;
	# NAT via masquerade
        oif "eth0" masquerade
    }
}
