#!/usr/sbin/nft -f
flush ruleset

#IPv4/6 common input rules
table inet filter {
  chain input {
    # default policy is drop
    type filter hook input priority filter; policy drop;
    # drop invalid
    ct state invalid drop
    # accept inbound packets related to existing connections
    ct state established,related accept
    # accept all localhost packets
    iifname "lo" accept
    # ensure required ICMPv6 packets are accepted
    ip6 nexthdr icmpv6 icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, echo-request, echo-reply,
    nd-router-solicit, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert } accept
    # only allow SSH from Chris' IPv4 or IPv6 subnet
    ip saddr 49.255.230.48/29 tcp dport 22 accept
    ip6 saddr 2402:7800:2014::/48 tcp dport 22 accept
    #accept HTTPS traffic for wstunnel on IPv4 only (no point listening on IPv6)
    meta nfproto ipv4 tcp dport 443 accept
    #51820/udp rule not required as WireGuard runs on localhost then traverses via wstunnel
  }
}

#IPv6 only forward rules - externalgateway routes ipv4 natively
table ip6 filter {
  chain forward {
    #default policy is drop
    type filter hook forward priority filter; policy drop;
    # important as IPv6 routers don't fragment
    tcp flags syn tcp option maxseg size set rt mtu
    # explicit rule for SSH from Chris' IPv6 subnet
    ip6 saddr 2402:7800:2014::/48 ip6 daddr 2404:9400:29c1:df00::/56 tcp dport 22 ct state new accept
    # forward all outbound IPv6 traffic from externalgateway
    iifname "wg0" oifname "eth0" accept
    # forward all inbound ipv6 traffic to externalgateway except invalid
    # firewalling done at externalgateway
    iifname "eth0" oifname "wg0" ct state invalid drop
    iifname "eth0" oifname "wg0" accept
  }
}

