[Interface]
# Local IPv6 address for WireGuard interface
Address = 2404:9400:29c1:df00::1/64
PrivateKey = <REDACTED>
MTU = 1280

[Peer]
PublicKey = d+lPLoY6Ra/Wgf1TleES99OBpqxYApwEZu3LvSXFFXo=
PresharedKey = <REDACTED>
# Azure labs blocks most outbound UDP so we route WireGuard
# over TCP 443 with wstunnel which listens locally on UDP 51820
Endpoint = 127.0.0.1:51820
# Route all IPv6 traffic over WireGuard connection
AllowedIPs = ::/0
# Maintain consistent remote connection
PersistentKeepalive = 25
