[Interface]
Address = 2404:9400:29c1:df00::254/64
# WireGuard listen port, will be routed over WS Tunnel at :443
ListenPort = 51820
PrivateKey = <REDACTED>
MTU = 1280
[Peer]
PublicKey = tAfyBZkLBZFOjHYGWiO2xtu5stanS8TOsloTk07GSys=
PresharedKey = <REDACTED>
# Allow transit for our IPv6 /56 allocation
AllowedIPs = 2404:9400:29c1:df00::/56
